//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Products
    {
        public int id { get; set; }
        public string productName { get; set; }
        public int categoryId { get; set; }
        public decimal unitPrice { get; set; }
        public int unitInStock { get; set; }

        [JsonIgnore]
        public virtual Categories Categories { get; set; }
    }
}
